AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'review_apps/**/*'

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml
